export const mediums = [
  { value: "", text: "-- Please select a medium --" },
  { value: "Painting", text: "Painting" },
  { value: "Sculpture", text: "Sculpture" },
  { value: "Drawing", text: "Drawing" },
  { value: "Prints", text: "Prints" },
  { value: "Work on paper", text: "Work on paper" },
  { value: "Design", text: "Design" },
  { value: "Photography", text: "Photography" },
  { value: "Installation", text: "Installation" },
  { value: "Film/Video", text: "Film/Video" },
  { value: "Other", text: "Other" },
]

export const countries = [
  { value: "", text: "-- Please select a country --" },
  { value: "Albania", text: "Albania" },
  { value: "Belarus", text: "Belarus" },
  { value: "Bosnia and Hercegovina", text: "Bosnia and Hercegovina" },
  { value: "Bulgaria", text: "Bulgaria" },
  { value: "Croatia", text: "Croatia" },
  { value: "Czech Republic", text: "Czech Republic" },
  { value: "Greece", text: "Greece" },
  { value: "Hungary", text: "Hungary" },
  { value: "Kosovo", text: "Kosovo" },
  { value: "Macedonia", text: "Macedonia" },
  { value: "Moldova", text: "Moldova" },
  { value: "Montenegro", text: "Montenegro" },
  { value: "Poland", text: "Poland" },
  { value: "Romania", text: "Romania" },
  { value: "Russia", text: "Russia" },
  { value: "Serbia", text: "Serbia" },
  { value: "Slovakia", text: "Slovakia" },
  { value: "Slovenia", text: "Slovenia" },
  { value: "Turkey", text: "Turkey" },
  { value: "Ukraine", text: "Ukraine" },
]
