export const mediums = [
  { value: "", text: "-- Please select a medium --" },
  { value: "painting", text: "Painting" },
  { value: "sculpture", text: "Sculpture" },
  { value: "drawing", text: "Drawing" },
  { value: "prints", text: "Prints" },
  { value: "workOnPaper", text: "Work on paper" },
  { value: "design", text: "Design" },
  { value: "photography", text: "Photography" },
  { value: "installation", text: "Installation" },
  { value: "filmVideo", text: "Film/Video" },
  { value: "other", text: "Other" },
]

export const countries = [
  { value: "", text: "-- Please select a country --" },
  { value: "albania", text: "Albania" },
  { value: "belarus", text: "Belarus" },
  { value: "bosniaAndHercegovina", text: "Bosnia and Hercegovina" },
  { value: "bulgaria", text: "Bulgaria" },
  { value: "croatia", text: "Croatia" },
  { value: "czechRepublic", text: "Czech Republic" },
  { value: "greece", text: "Greece" },
  { value: "hungary", text: "Hungary" },
  { value: "kosovo", text: "Kosovo" },
  { value: "macedonia", text: "Macedonia" },
  { value: "moldova", text: "Moldova" },
  { value: "montenegro", text: "Montenegro" },
  { value: "poland", text: "Poland" },
  { value: "romania", text: "Romania" },
  { value: "russia", text: "Russia" },
  { value: "serbia", text: "Serbia" },
  { value: "slovakia", text: "Slovakia" },
  { value: "slovenia", text: "Slovenia" },
  { value: "turkey", text: "Turkey" },
  { value: "ukraine", text: "Ukraine" },
]
